//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRoutines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routine
    {
        public int DailyRoutineId { get; set; }
        public string Day { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> RestPulse { get; set; }
        public string Breakfast { get; set; }
        public string Lunch { get; set; }
        public string Dinner { get; set; }
        public string Snack { get; set; }
        public Nullable<double> Water { get; set; }
        public string QiGong { get; set; }
        public string PullUps { get; set; }
        public string Endurance { get; set; }
        public string Meditate { get; set; }
        public string Notes { get; set; }
    }
}
